# Generated by Django 4.0.6 on 2022-07-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='desc',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
